-- ============================================================
-- What The Fudge Trivia: database schema (target state)
--
-- This is the schema a FRESH project should have: the live database after
-- the puzzle-id cutover (supabase/puzzle_id_cutover: C1, C2) and the
-- minimal security lockdown (L1). Column types match the live database
-- (dates are stored as 'YYYY-MM-DD' text on games and plays).
--
-- DO NOT run this against the live database to "update" it: use the
-- numbered cutover scripts, which move live data safely.
--
-- Model:
--   * games.id is a puzzle's permanent identity. games.date is only when it
--     is scheduled; at most one PUBLISHED puzzle per date.
--   * every play (game_records) and every community stats row
--     (puzzle_stats) belongs to a puzzle id. Moving a puzzle to another date
--     never touches its plays or stats.
--   * one play per player per puzzle.
--   * a puzzle with plays can't be deleted: retire it (status 'retired').
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.games (
  id text primary key,
  date text not null,
  theme_title text not null,
  category_a text not null,
  category_b text not null,
  category_a_color text,
  category_b_color text,
  category_a_image text,
  category_b_image text,
  header_image text,
  category_a_share_name text,
  category_b_share_name text,
  status text not null default 'draft',
  questions jsonb not null default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint games_status_check check (status in ('draft', 'published', 'retired')),
  constraint games_published_date_iso check (status <> 'published' or date ~ '^\d{4}-\d{2}-\d{2}$')
);

create unique index if not exists games_one_published_per_date
  on public.games (date) where status = 'published';

create table if not exists public.players (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  is_guest boolean not null default true,
  created_at timestamptz default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.game_records (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  puzzle_id text not null references public.games(id) on delete restrict,
  game_date text not null,
  theme_title text,
  score integer not null default 0,
  total_questions integer not null default 0,
  answers jsonb not null default '[]'::jsonb,
  completed boolean not null default false,
  started_at timestamptz default now(),
  completed_at timestamptz,
  constraint game_records_player_puzzle_key unique (player_id, puzzle_id)
);

comment on column public.game_records.puzzle_id is 'The puzzle (games.id) this play belongs to. Permanent.';
comment on column public.game_records.game_date is 'Snapshot of the puzzle''s scheduled date when the play started. Display only, never a key.';

create index if not exists game_records_puzzle_completed_idx
  on public.game_records (puzzle_id) where completed;

create table if not exists public.player_stats (
  player_id uuid primary key references public.players(id) on delete cascade,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_played_date text,
  total_played integer not null default 0,
  total_correct integer not null default 0,
  total_questions integer not null default 0,
  best_combo integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.puzzle_stats (
  puzzle_id text primary key references public.games(id) on delete cascade,
  total_finished integer not null default 0,
  total_score integer not null default 0,
  perfect_count integer not null default 0,
  total_questions integer not null default 0,
  question_correct_counts jsonb not null default '[]'::jsonb,
  question_answer_counts jsonb not null default '[]'::jsonb,
  score_histogram jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Fills the date snapshot on a new play and keeps a play on its puzzle.
create or replace function public.game_records_assign_puzzle()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' then
    -- A play never moves to another puzzle.
    new.puzzle_id := old.puzzle_id;
    return new;
  end if;
  if new.game_date is null then
    select g.date into new.game_date from public.games g where g.id = new.puzzle_id;
  end if;
  return new;
end;
$$;

-- Rebuilds one puzzle's stats row from its completed plays.
create or replace function public.rebuild_puzzle_stats_for(target_puzzle_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_puzzle_id is null then
    return;
  end if;

  -- One rebuild of a puzzle at a time: a second finish waits here until the
  -- first commits, then counts both. Without this, two simultaneous
  -- finishes could collide and roll back the later player's save.
  perform pg_advisory_xact_lock(hashtext('puzzle_stats:' || target_puzzle_id));

  delete from public.puzzle_stats where puzzle_id = target_puzzle_id;

  insert into public.puzzle_stats (
    puzzle_id,
    total_finished,
    total_score,
    perfect_count,
    total_questions,
    question_correct_counts,
    question_answer_counts,
    score_histogram,
    updated_at
  )
  with completed_records as (
    select *
    from public.game_records
    where completed = true
      and puzzle_id = target_puzzle_id
  ),
  base as (
    select
      count(*)::int as total_finished,
      coalesce(sum(score), 0)::int as total_score,
      count(*) filter (
        where total_questions > 0 and score = total_questions
      )::int as perfect_count,
      coalesce(max(total_questions), 0)::int as total_questions
    from completed_records
  ),
  idxs as (
    select generate_series(
      0,
      greatest((select total_questions from base) - 1, 0)
    ) as idx
  ),
  question_rollup as (
    select
      i.idx,
      count(a.elem)::int as answered_count,
      count(*) filter (
        where coalesce((a.elem ->> 'correct')::boolean, false)
      )::int as correct_count
    from idxs i
    left join completed_records cr on true
    left join lateral (
      select elem
      from jsonb_array_elements(cr.answers) with ordinality arr(elem, ord)
      where ord = i.idx + 1
    ) a on true
    group by i.idx
    order by i.idx
  ),
  score_rollup as (
    select score::text as bucket, count(*)::int as count_value
    from completed_records
    group by score
    order by score
  )
  select
    target_puzzle_id,
    b.total_finished,
    b.total_score,
    b.perfect_count,
    b.total_questions,
    case
      when b.total_questions > 0 then (
        select jsonb_agg(q.correct_count order by q.idx)
        from question_rollup q
      )
      else '[]'::jsonb
    end,
    case
      when b.total_questions > 0 then (
        select jsonb_agg(q.answered_count order by q.idx)
        from question_rollup q
      )
      else '[]'::jsonb
    end,
    coalesce(
      (select jsonb_object_agg(s.bucket, s.count_value) from score_rollup s),
      '{}'::jsonb
    ),
    now()
  from base b
  where b.total_finished > 0;
end;
$$;

-- Rebuilds every puzzle's stats.
create or replace function public.rebuild_puzzle_stats()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  pid text;
begin
  delete from public.puzzle_stats ps
   where not exists (select 1 from public.game_records r
                      where r.completed and r.puzzle_id = ps.puzzle_id);
  for pid in
    select distinct puzzle_id from public.game_records where completed order by 1
  loop
    perform public.rebuild_puzzle_stats_for(pid);
  end loop;
end;
$$;

-- Rebuilds the affected puzzle when a play is finished, changed or deleted.
-- Bulk scripts may set wtf.defer_stats = on for their own transaction and
-- rebuild once at the end.
create or replace function public.handle_completed_game_record()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(current_setting('wtf.defer_stats', true), '') = 'on' then
    return null;
  end if;

  if tg_op = 'DELETE' then
    if old.completed then
      perform public.rebuild_puzzle_stats_for(old.puzzle_id);
    end if;
    return null;
  end if;

  if tg_op = 'UPDATE' and old.completed and not new.completed then
    perform public.rebuild_puzzle_stats_for(old.puzzle_id);
  elsif new.completed and (
       tg_op = 'INSERT'
       or not coalesce(old.completed, false)
       or old.score is distinct from new.score
       or old.answers is distinct from new.answers
       or old.total_questions is distinct from new.total_questions
     ) then
    perform public.rebuild_puzzle_stats_for(new.puzzle_id);
  end if;
  return null;
end;
$$;

revoke execute on function public.game_records_assign_puzzle()   from public, anon, authenticated;
revoke execute on function public.rebuild_puzzle_stats_for(text) from public, anon, authenticated;
revoke execute on function public.rebuild_puzzle_stats()         from public, anon, authenticated;
revoke execute on function public.handle_completed_game_record() from public, anon, authenticated;

drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at
before update on public.games
for each row
execute function public.set_updated_at();

drop trigger if exists player_stats_set_updated_at on public.player_stats;
create trigger player_stats_set_updated_at
before update on public.player_stats
for each row
execute function public.set_updated_at();

drop trigger if exists puzzle_stats_set_updated_at on public.puzzle_stats;
create trigger puzzle_stats_set_updated_at
before update on public.puzzle_stats
for each row
execute function public.set_updated_at();

drop trigger if exists game_records_assign_puzzle on public.game_records;
create trigger game_records_assign_puzzle
before insert or update on public.game_records
for each row
execute function public.game_records_assign_puzzle();

drop trigger if exists game_records_completed_stats on public.game_records;
create trigger game_records_completed_stats
after insert or update or delete on public.game_records
for each row
execute function public.handle_completed_game_record();

alter table public.games enable row level security;
alter table public.players enable row level security;
alter table public.game_records enable row level security;
alter table public.player_stats enable row level security;
alter table public.puzzle_stats enable row level security;

-- Puzzles. NOTE: still readable AND writable by anyone, because Admin saves
-- from the browser with the public key behind a client-side password. Next
-- security step: an Admin sign-in, then write access for Admin only and
-- read access to published puzzles only.
drop policy if exists "games are readable" on public.games;
create policy "games are readable"
on public.games
for select
to anon, authenticated
using (true);

drop policy if exists "games are writable" on public.games;
create policy "games are writable"
on public.games
for all
to anon, authenticated
using (true)
with check (true);

-- Players, plays and streak stats: each signed-in player (guests sign in
-- anonymously) sees and changes only their own rows.
drop policy if exists "players own profile" on public.players;
create policy "players own profile"
on public.players
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "players create profile" on public.players;
create policy "players create profile"
on public.players
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "players update profile" on public.players;
create policy "players update profile"
on public.players
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "game records own rows" on public.game_records;
create policy "game records own rows"
on public.game_records
for select
to authenticated
using (auth.uid() = player_id);

drop policy if exists "game records insert own rows" on public.game_records;
create policy "game records insert own rows"
on public.game_records
for insert
to authenticated
with check (auth.uid() = player_id);

drop policy if exists "game records update own rows" on public.game_records;
create policy "game records update own rows"
on public.game_records
for update
to authenticated
using (auth.uid() = player_id)
with check (auth.uid() = player_id);

drop policy if exists "player stats own rows" on public.player_stats;
create policy "player stats own rows"
on public.player_stats
for select
to authenticated
using (auth.uid() = player_id);

drop policy if exists "player stats insert own rows" on public.player_stats;
create policy "player stats insert own rows"
on public.player_stats
for insert
to authenticated
with check (auth.uid() = player_id);

drop policy if exists "player stats update own rows" on public.player_stats;
create policy "player stats update own rows"
on public.player_stats
for update
to authenticated
using (auth.uid() = player_id)
with check (auth.uid() = player_id);

-- Community stats are public (they hold no personal data).
drop policy if exists "puzzle stats are readable" on public.puzzle_stats;
create policy "puzzle stats are readable"
on public.puzzle_stats
for select
to anon, authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('wtf-images', 'wtf-images', true)
on conflict (id) do nothing;
