-- ============================================================================
--  WTF Trivia: the LIVE schema as declared (section A of 0001), for the local rehearsal only
-- ============================================================================
--  GENERATED by tools/build-phase2-install.mjs from supabase/migrations/.
--  Do not edit by hand: edit the migrations and rebuild.
--  Built 2026-10-06T15:21:50.752Z.
--
--  tools/rehearse-local.mjs applies this to a blank local database (with the
--  hosted project's default privileges re-created), loads a hosted content
--  export, then runs phase2-install.sql and proves the content fingerprint
--  did not move. Never run against the hosted project: it already is this.
-- ============================================================================

create extension if not exists pgcrypto with schema extensions;

-- ============================================================================
-- A. THE LIVE SCHEMA (declared; no-ops where it already exists)
-- ============================================================================

-- ---- A1. Content: one row per puzzle; the questions live inside the row ----
create table if not exists public.games (
  id text primary key,
  date text not null,
  theme_title text not null,
  category_a text not null,
  category_b text not null,
  category_a_color text,
  category_b_color text,
  category_a_image text,
  category_b_image text,
  header_image text,
  status text not null default 'draft',
  questions jsonb not null default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  category_a_share_name text,
  category_b_share_name text,
  tags text[] not null default '{}'::text[],
  category_a_subtitle text,
  category_b_subtitle text,
  category_a_button_name text,
  category_b_button_name text,
  constraint games_status_check check (status in ('draft', 'published', 'retired')),
  constraint games_published_date_iso check (status <> 'published' or date ~ '^\d{4}-\d{2}-\d{2}$')
);

create unique index if not exists games_one_published_per_date
  on public.games (date) where status = 'published';

-- ---- A2. Players (guests sign in anonymously; players.id = auth.uid()) ----
create table if not exists public.players (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  email text,
  is_guest boolean not null default true,
  last_seen_at timestamptz not null default now()
);

create table if not exists public.game_records (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  game_date text not null,
  theme_title text,
  score integer not null default 0,
  total_questions integer not null default 0,
  answers jsonb not null default '[]'::jsonb,
  completed boolean not null default false,
  started_at timestamptz default now(),
  completed_at timestamptz,
  puzzle_id text not null references public.games(id) on delete restrict,
  constraint game_records_player_puzzle_key unique (player_id, puzzle_id)
);

create index if not exists game_records_puzzle_completed_idx
  on public.game_records (puzzle_id) where completed;

create table if not exists public.player_stats (
  player_id uuid primary key references public.players(id) on delete cascade,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_played_date text,
  total_played integer not null default 0,
  total_correct integer not null default 0,
  total_questions integer not null default 0,
  best_combo integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.puzzle_stats (
  puzzle_id text primary key references public.games(id) on delete cascade,
  total_finished integer not null default 0,
  total_score integer not null default 0,
  perfect_count integer not null default 0,
  total_questions integer not null default 0,
  question_correct_counts jsonb not null default '[]'::jsonb,
  question_answer_counts jsonb not null default '[]'::jsonb,
  score_histogram jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.puzzle_favorites (
  player_id uuid not null references public.players(id) on delete cascade,
  puzzle_id text not null references public.games(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (player_id, puzzle_id)
);

create index if not exists puzzle_favorites_puzzle_idx
  on public.puzzle_favorites (puzzle_id);

create table if not exists public.puzzle_favorite_counts (
  puzzle_id text primary key references public.games(id) on delete cascade,
  favorite_count integer not null default 0 check (favorite_count >= 0),
  updated_at timestamptz not null default now()
);

-- ---- A3. Functions, exactly the live bodies ----
create or replace function public.bump_jsonb_array_value(source jsonb, array_index integer, bump_by integer default 1)
returns jsonb language plpgsql as $$
declare
  working jsonb := coalesce(source, '[]'::jsonb);
  current_length integer := coalesce(jsonb_array_length(working), 0);
  current_value integer;
begin
  if array_index < 0 then
    return working;
  end if;
  while current_length <= array_index loop
    working := working || to_jsonb(0);
    current_length := current_length + 1;
  end loop;
  current_value := coalesce((working ->> array_index)::integer, 0);
  working := jsonb_set(working, array[array_index::text], to_jsonb(current_value + coalesce(bump_by, 0)));
  return working;
end;
$$;

create or replace function public.bump_jsonb_object_count(source jsonb, bucket text, bump_by integer default 1)
returns jsonb language sql as $$
  select jsonb_set(
    coalesce(source, '{}'::jsonb),
    array[bucket],
    to_jsonb(coalesce((coalesce(source, '{}'::jsonb) ->> bucket)::integer, 0) + coalesce(bump_by, 0)),
    true
  );
$$;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.game_records_assign_puzzle()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'UPDATE' then
    -- A play never moves to another puzzle.
    new.puzzle_id := old.puzzle_id;
    return new;
  end if;
  if new.game_date is null then
    select g.date into new.game_date from public.games g where g.id = new.puzzle_id;
  end if;
  return new;
end;
$$;

create or replace function public.rebuild_puzzle_stats_for(target_puzzle_id text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if target_puzzle_id is null then
    return;
  end if;

  -- One rebuild of a puzzle at a time (simultaneous-finisher fix).
  perform pg_advisory_xact_lock(hashtext('puzzle_stats:' || target_puzzle_id));

  delete from public.puzzle_stats where puzzle_id = target_puzzle_id;

  insert into public.puzzle_stats (
    puzzle_id,
    total_finished,
    total_score,
    perfect_count,
    total_questions,
    question_correct_counts,
    question_answer_counts,
    score_histogram,
    updated_at
  )
  with completed_records as (
    select *
    from public.game_records
    where completed = true
      and puzzle_id = target_puzzle_id
  ),
  base as (
    select
      count(*)::int as total_finished,
      coalesce(sum(score), 0)::int as total_score,
      count(*) filter (
        where total_questions > 0 and score = total_questions
      )::int as perfect_count,
      coalesce(max(total_questions), 0)::int as total_questions
    from completed_records
  ),
  idxs as (
    select generate_series(
      0,
      greatest((select total_questions from base) - 1, 0)
    ) as idx
  ),
  question_rollup as (
    select
      i.idx,
      count(a.elem)::int as answered_count,
      count(*) filter (
        where coalesce((a.elem ->> 'correct')::boolean, false)
      )::int as correct_count
    from idxs i
    left join completed_records cr on true
    left join lateral (
      select elem
      from jsonb_array_elements(cr.answers) with ordinality arr(elem, ord)
      where ord = i.idx + 1
    ) a on true
    group by i.idx
    order by i.idx
  ),
  score_rollup as (
    select score::text as bucket, count(*)::int as count_value
    from completed_records
    group by score
    order by score
  )
  select
    target_puzzle_id,
    b.total_finished,
    b.total_score,
    b.perfect_count,
    b.total_questions,
    case
      when b.total_questions > 0 then (
        select jsonb_agg(q.correct_count order by q.idx)
        from question_rollup q
      )
      else '[]'::jsonb
    end,
    case
      when b.total_questions > 0 then (
        select jsonb_agg(q.answered_count order by q.idx)
        from question_rollup q
      )
      else '[]'::jsonb
    end,
    coalesce(
      (select jsonb_object_agg(s.bucket, s.count_value) from score_rollup s),
      '{}'::jsonb
    ),
    now()
  from base b
  where b.total_finished > 0;
end;
$$;

create or replace function public.rebuild_puzzle_stats()
returns void language plpgsql security definer set search_path = public as $$
declare
  pid text;
begin
  delete from public.puzzle_stats ps
   where not exists (select 1 from public.game_records r
                      where r.completed and r.puzzle_id = ps.puzzle_id);
  for pid in
    select distinct puzzle_id from public.game_records where completed order by 1
  loop
    perform public.rebuild_puzzle_stats_for(pid);
  end loop;
end;
$$;

create or replace function public.handle_completed_game_record()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if coalesce(current_setting('wtf.defer_stats', true), '') = 'on' then
    return null;
  end if;

  if tg_op = 'DELETE' then
    if old.completed then
      perform public.rebuild_puzzle_stats_for(old.puzzle_id);
    end if;
    return null;
  end if;

  if tg_op = 'UPDATE' and old.completed and not new.completed then
    perform public.rebuild_puzzle_stats_for(old.puzzle_id);
  elsif new.completed and (
       tg_op = 'INSERT'
       or not coalesce(old.completed, false)
       or old.score is distinct from new.score
       or old.answers is distinct from new.answers
       or old.total_questions is distinct from new.total_questions
     ) then
    perform public.rebuild_puzzle_stats_for(new.puzzle_id);
  end if;
  return null;
end;
$$;

create or replace function public.puzzle_favorites_count()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.puzzle_favorite_counts as c (puzzle_id, favorite_count, updated_at)
    values (new.puzzle_id, 1, now())
    on conflict (puzzle_id) do update
      set favorite_count = c.favorite_count + 1, updated_at = now();
    return null;
  end if;
  -- DELETE. A plain update: when the puzzle itself is being deleted its
  -- counts row may already be gone, and that's fine.
  update public.puzzle_favorite_counts
     set favorite_count = greatest(favorite_count - 1, 0), updated_at = now()
   where puzzle_id = old.puzzle_id;
  return null;
end;
$$;

create or replace function public.set_puzzle_favorite(target_puzzle_id text, favorite boolean)
returns integer language plpgsql set search_path = public as $$
declare
  me uuid := auth.uid();
  total integer;
begin
  if me is null then
    raise exception 'Sign in (or play as a guest) to favorite puzzles.' using errcode = '42501';
  end if;
  if favorite then
    insert into public.puzzle_favorites (player_id, puzzle_id)
    values (me, target_puzzle_id)
    on conflict (player_id, puzzle_id) do nothing;
  else
    delete from public.puzzle_favorites
     where player_id = me and puzzle_id = target_puzzle_id;
  end if;
  select c.favorite_count into total
    from public.puzzle_favorite_counts c
   where c.puzzle_id = target_puzzle_id;
  return coalesce(total, 0);
end;
$$;

-- ---- A4. Triggers, exactly as live ----
drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at
before update on public.games for each row execute function public.set_updated_at();

drop trigger if exists player_stats_set_updated_at on public.player_stats;
create trigger player_stats_set_updated_at
before update on public.player_stats for each row execute function public.set_updated_at();

drop trigger if exists puzzle_stats_set_updated_at on public.puzzle_stats;
create trigger puzzle_stats_set_updated_at
before update on public.puzzle_stats for each row execute function public.set_updated_at();

drop trigger if exists game_records_assign_puzzle on public.game_records;
create trigger game_records_assign_puzzle
before insert or update on public.game_records for each row execute function public.game_records_assign_puzzle();

drop trigger if exists game_records_completed_stats on public.game_records;
create trigger game_records_completed_stats
after insert or update or delete on public.game_records for each row execute function public.handle_completed_game_record();

drop trigger if exists puzzle_favorites_count on public.puzzle_favorites;
create trigger puzzle_favorites_count
after insert or delete on public.puzzle_favorites for each row execute function public.puzzle_favorites_count();

-- ---- A5. RLS and the live policies (both the old permissive set and the own-row set,
--          exactly as the hosted project has them today; 0002 removes the permissive duplicates) ----
alter table public.games enable row level security;
alter table public.players enable row level security;
alter table public.game_records enable row level security;
alter table public.player_stats enable row level security;
alter table public.puzzle_stats enable row level security;
alter table public.puzzle_favorites enable row level security;
alter table public.puzzle_favorite_counts enable row level security;

-- games (the beta-era open policies; the admin gate is migration 0003)
drop policy if exists "Anyone can delete games" on public.games;
create policy "Anyone can delete games" on public.games for delete using (true);
drop policy if exists "Anyone can insert games" on public.games;
create policy "Anyone can insert games" on public.games for insert with check (true);
drop policy if exists "Anyone can read all games for admin" on public.games;
create policy "Anyone can read all games for admin" on public.games for select using (true);
drop policy if exists "Anyone can read published games" on public.games;
create policy "Anyone can read published games" on public.games for select using (status = 'published');
drop policy if exists "Anyone can update games" on public.games;
create policy "Anyone can update games" on public.games for update using (true);
drop policy if exists "games are readable" on public.games;
create policy "games are readable" on public.games for select to anon, authenticated using (true);
drop policy if exists "games are writable" on public.games;
create policy "games are writable" on public.games for all to anon, authenticated using (true) with check (true);

-- players
drop policy if exists "Anyone can create a player" on public.players;
create policy "Anyone can create a player" on public.players for insert with check (true);
drop policy if exists "Players can read own row" on public.players;
create policy "Players can read own row" on public.players for select using (true);
drop policy if exists "players create profile" on public.players;
create policy "players create profile" on public.players for insert to authenticated with check (auth.uid() = id);
drop policy if exists "players own profile" on public.players;
create policy "players own profile" on public.players for select to authenticated using (auth.uid() = id);
drop policy if exists "players update profile" on public.players;
create policy "players update profile" on public.players for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

-- game_records
drop policy if exists "Players can insert own records" on public.game_records;
create policy "Players can insert own records" on public.game_records for insert with check (true);
drop policy if exists "Players can read own records" on public.game_records;
create policy "Players can read own records" on public.game_records for select using (true);
drop policy if exists "Players can update own records" on public.game_records;
create policy "Players can update own records" on public.game_records for update using (true);
drop policy if exists "game records insert own rows" on public.game_records;
create policy "game records insert own rows" on public.game_records for insert to authenticated with check (auth.uid() = player_id);
drop policy if exists "game records own rows" on public.game_records;
create policy "game records own rows" on public.game_records for select to authenticated using (auth.uid() = player_id);
drop policy if exists "game records update own rows" on public.game_records;
create policy "game records update own rows" on public.game_records for update to authenticated using (auth.uid() = player_id) with check (auth.uid() = player_id);

-- player_stats
drop policy if exists "Players can insert own stats" on public.player_stats;
create policy "Players can insert own stats" on public.player_stats for insert with check (true);
drop policy if exists "Players can read own stats" on public.player_stats;
create policy "Players can read own stats" on public.player_stats for select using (true);
drop policy if exists "Players can update own stats" on public.player_stats;
create policy "Players can update own stats" on public.player_stats for update using (true);
drop policy if exists "player stats insert own rows" on public.player_stats;
create policy "player stats insert own rows" on public.player_stats for insert to authenticated with check (auth.uid() = player_id);
drop policy if exists "player stats own rows" on public.player_stats;
create policy "player stats own rows" on public.player_stats for select to authenticated using (auth.uid() = player_id);
drop policy if exists "player stats update own rows" on public.player_stats;
create policy "player stats update own rows" on public.player_stats for update to authenticated using (auth.uid() = player_id) with check (auth.uid() = player_id);

-- community tables and favorites
drop policy if exists "puzzle stats are readable" on public.puzzle_stats;
create policy "puzzle stats are readable" on public.puzzle_stats for select to anon, authenticated using (true);
drop policy if exists "puzzle favorite counts are readable" on public.puzzle_favorite_counts;
create policy "puzzle favorite counts are readable" on public.puzzle_favorite_counts for select to anon, authenticated using (true);
drop policy if exists "puzzle favorites own rows" on public.puzzle_favorites;
create policy "puzzle favorites own rows" on public.puzzle_favorites for select to authenticated using (auth.uid() = player_id);
drop policy if exists "puzzle favorites insert own rows" on public.puzzle_favorites;
create policy "puzzle favorites insert own rows" on public.puzzle_favorites for insert to authenticated with check (auth.uid() = player_id);
drop policy if exists "puzzle favorites delete own rows" on public.puzzle_favorites;
create policy "puzzle favorites delete own rows" on public.puzzle_favorites for delete to authenticated using (auth.uid() = player_id);

-- ---- A6. Grants exactly as live (the project's default ACL gives anon and
--          authenticated every privilege on games and the player tables; favorites
--          were set explicitly by supabase/puzzle_favorites.sql) ----
grant all on table public.games, public.players, public.game_records, public.player_stats, public.puzzle_stats
  to anon, authenticated, service_role;
grant usage, select, update on sequence public.game_records_id_seq to anon, authenticated, service_role;
revoke all on table public.puzzle_favorites from anon, authenticated;
grant select, insert, delete on table public.puzzle_favorites to authenticated;
grant all on table public.puzzle_favorites to service_role;
revoke all on table public.puzzle_favorite_counts from anon, authenticated;
grant select on table public.puzzle_favorite_counts to anon, authenticated;
grant all on table public.puzzle_favorite_counts to service_role;

revoke execute on function public.game_records_assign_puzzle()   from public, anon, authenticated;
revoke execute on function public.rebuild_puzzle_stats_for(text) from public, anon, authenticated;
revoke execute on function public.rebuild_puzzle_stats()         from public, anon, authenticated;
revoke execute on function public.handle_completed_game_record() from public, anon, authenticated;
revoke execute on function public.puzzle_favorites_count()       from public, anon, authenticated;
revoke execute on function public.set_puzzle_favorite(text, boolean) from public, anon;
grant  execute on function public.set_puzzle_favorite(text, boolean) to authenticated, service_role;

-- ---- A7. The image bucket and its live policies (only where the storage schema exists;
--          the local test stack runs without the storage service) ----
do $$
begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public) values ('wtf-images', 'wtf-images', true) on conflict (id) do nothing;
  end if;
  if to_regclass('storage.objects') is not null then
    if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Anyone can read images') then
      create policy "Anyone can read images" on storage.objects for select using (bucket_id = 'wtf-images');
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Anyone can upload images') then
      create policy "Anyone can upload images" on storage.objects for insert with check (bucket_id = 'wtf-images');
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Anyone can delete images') then
      create policy "Anyone can delete images" on storage.objects for delete using (bucket_id = 'wtf-images');
    end if;
  end if;
end $$;

