-- ============================================================================
--  WTF Trivia: HOSTED PHASE 2 INSTALL (one transaction; additive; content untouched)
-- ============================================================================
--  GENERATED by tools/build-phase2-install.mjs from supabase/migrations/.
--  Do not edit by hand: edit the migrations and rebuild.
--  Built 2026-10-06T15:21:50.750Z.
--
--  Runs through: node tools/hosted.mjs sql --file supabase/ops/hosted/phase2-install.sql
--  (rehearsal inside BEGIN … ROLLBACK by default; --apply commits). The tool
--  fingerprints every games row before and after and reports any movement.
--
--  Contents:
--    1. the account layer of 0001 (sections B–G): accounts, wtf_uid(),
--       account_email(), ensure_account(), my_account(), ping(), admins,
--       is_wtf_admin(), best_combo(), recompute_player_stats(),
--       guest_handoffs + offer/resolve/import/decline, delete_*_account, grants
--    2. 0002: the player-table lockdown (drops the permissive duplicate
--       policies; explicit grants on the player tables)
--    3. the migration ledger rows 0001 and 0002, so `supabase db push`
--       and `supabase migration list` agree with the repository afterwards
--
--  NOT here: section A of 0001 (the live schema: the hosted project already
--  has it, and content is never recreated) and 0003 (the admin gate; applied
--  later, on its own, once an admin account exists).
--
--  Pre-condition checked below: the live tables exist with the expected
--  keys (ids are text; plays key on puzzle_id), and none of the new objects
--  exist yet.
-- ============================================================================

do $$
begin
  if to_regclass('public.games') is null or to_regclass('public.players') is null or to_regclass('public.game_records') is null then
    raise exception 'phase2-install aborted: the live tables are missing; this is not the WTF project';
  end if;
  if (select udt_name from information_schema.columns where table_schema='public' and table_name='games' and column_name='id') <> 'text' then
    raise exception 'phase2-install aborted: games.id is not text; the live shape differs from the inventory';
  end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='game_records' and column_name='puzzle_id') then
    raise exception 'phase2-install aborted: game_records.puzzle_id is missing; the puzzle-id cutover is not in place';
  end if;
  if to_regclass('public.accounts') is not null or to_regclass('public.guest_handoffs') is not null or to_regclass('public.admins') is not null then
    raise exception 'phase2-install aborted: the account layer already exists';
  end if;
end $$;

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- 1. 0001_wtf_baseline.sql, sections B–G
-- ---------------------------------------------------------------------------
-- ============================================================================
-- B. THE LOCAL ACCOUNT
-- ============================================================================
create table public.accounts (
  user_id         uuid primary key references auth.users(id) on delete cascade,
  global_user_id  text not null,
  created_at      timestamptz not null default now(),
  last_seen_at    timestamptz not null default now(),
  constraint accounts_global_user_id_key    unique (global_user_id),
  constraint accounts_global_user_id_format check (global_user_id ~ '^user_[0-9A-Za-z]{10,64}$')
);
comment on table  public.accounts is 'A WTF Trivia account. An auth user is an account only when it has a row here; the only writer is ensure_account(). The same uuid is the player id (players.id).';
comment on column public.accounts.global_user_id is 'The shared identity provider''s user id (user_...). The cross-game link; never a key for gameplay data.';

alter table public.accounts enable row level security;   -- no policies: reachable only through RPCs

-- The account boundary.
create function public.wtf_uid() returns uuid
language sql stable security definer set search_path = public as $$
  select a.user_id
    from public.accounts a
   where a.user_id = auth.uid()
$$;
comment on function public.wtf_uid() is 'The caller''s account id, or NULL when the caller is a guest (anonymous user) or any auth user that is not a WTF account. Account-only RPCs and policies use this.';

-- The ONE source of an account's current email: the provider identity, which
-- GoTrue refreshes on every sign-in; auth.users.email is only a fallback.
create function public.account_email(_user_id uuid) returns text
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select nullif(btrim(i.identity_data ->> 'email'), '')
       from auth.identities i
      where i.user_id = _user_id
        and i.provider = 'custom:platform'
      order by i.created_at
      limit 1),
    (select u.email::text
       from auth.users u
      where u.id = _user_id)
  )
$$;

-- Create or refresh the account behind the current session. Also keeps the
-- player row in step: an account's player is not a guest and carries the
-- identity-first email (display only).
create function public.ensure_account()
returns table(outcome text, user_id uuid, global_user_id text, email text, created_at timestamptz)
language plpgsql security definer set search_path = public as $$
#variable_conflict use_column
declare
  _uid uuid := auth.uid();
  _gid text;
begin
  if _uid is null then
    return query select 'not_signed_in'::text, null::uuid, null::text, null::text, null::timestamptz;
    return;
  end if;

  -- The link is read from GoTrue's identity table, never from the client.
  select i.provider_id
    into _gid
    from auth.identities i
   where i.user_id = _uid
     and i.provider = 'custom:platform'
   order by i.created_at
   limit 1;

  if _gid is null then
    -- A guest (anonymous user) or an auth user that did not come through the
    -- shared sign-in (the old email/password beta users, dashboard users).
    -- Not, and never becomes, an account.
    return query select 'not_platform_linked'::text, null::uuid, null::text, null::text, null::timestamptz;
    return;
  end if;

  insert into public.accounts (user_id, global_user_id)
  values (_uid, _gid)
  on conflict (user_id) do update
    set last_seen_at = now();

  insert into public.players (id, email, is_guest, last_seen_at)
  values (_uid, public.account_email(_uid), false, now())
  on conflict (id) do update
    set email = excluded.email, is_guest = false, last_seen_at = now();

  return query
    select 'ok'::text, a.user_id, a.global_user_id, public.account_email(a.user_id), a.created_at
      from public.accounts a
     where a.user_id = _uid;
end;
$$;

create function public.my_account()
returns table(user_id uuid, global_user_id text, email text, created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select a.user_id, a.global_user_id, public.account_email(a.user_id), a.created_at
    from public.accounts a
   where a.user_id = auth.uid()
$$;

create function public.ping() returns boolean
language sql stable set search_path = public as $$ select true $$;

-- ============================================================================
-- C. ADMINS (the gate itself is migration 0003, applied only when approved)
-- ============================================================================
create table public.admins (
  user_id     uuid primary key references public.accounts(user_id) on delete cascade,
  granted_at  timestamptz not null default now()
);
comment on table public.admins is 'Accounts allowed to write official content once 0003 is applied. Granted by the owner in SQL: insert into public.admins (user_id) select user_id from public.accounts where global_user_id = ''user_...'';';
alter table public.admins enable row level security;

create function public.is_wtf_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins ad where ad.user_id = public.wtf_uid())
$$;

-- ============================================================================
-- D. PLAYER STATS, RECOMPUTED FROM PLAYS
--    The app maintains player_stats incrementally on every finish. When two
--    players' plays become one person's (an import), the counters are rebuilt
--    from the merged plays instead of being summed: Games = finished plays,
--    Accuracy = correct / asked, Best Combo = the longest run of correct answers
--    in any play, Streak = consecutive puzzle dates ending at the last play.
-- ============================================================================
create function public.best_combo(_answers jsonb) returns integer
language plpgsql immutable as $$
declare
  _best integer := 0;
  _cur integer := 0;
  _el jsonb;
begin
  if _answers is null or jsonb_typeof(_answers) <> 'array' then
    return 0;
  end if;
  for _el in select * from jsonb_array_elements(_answers) loop
    if coalesce((_el ->> 'correct')::boolean, false) then
      _cur := _cur + 1;
      if _cur > _best then _best := _cur; end if;
    else
      _cur := 0;
    end if;
  end loop;
  return _best;
end;
$$;

create function public.recompute_player_stats(_player_id uuid) returns void
language plpgsql security definer set search_path = public as $$
declare
  _played integer;
  _correct integer;
  _asked integer;
  _combo integer;
  _last text;
  _dates date[];
  _longest integer := 0;
  _current integer := 0;
  _run integer := 0;
  _i integer;
begin
  select count(*)::int, coalesce(sum(score), 0)::int, coalesce(sum(total_questions), 0)::int,
         coalesce(max(public.best_combo(answers)), 0)::int, max(game_date)
    into _played, _correct, _asked, _combo, _last
    from public.game_records
   where player_id = _player_id and completed;

  if _played = 0 then
    delete from public.player_stats where player_id = _player_id;
    return;
  end if;

  -- distinct, well-formed play dates in order (game_date is text on the live project)
  select array_agg(d order by d) into _dates
    from (select distinct (game_date)::date as d
            from public.game_records
           where player_id = _player_id and completed and game_date ~ '^\d{4}-\d{2}-\d{2}$') s;

  if _dates is not null then
    for _i in 1 .. array_length(_dates, 1) loop
      if _i > 1 and _dates[_i] = _dates[_i - 1] + 1 then
        _run := _run + 1;
      else
        _run := 1;
      end if;
      if _run > _longest then _longest := _run; end if;
    end loop;
    _current := _run;   -- the run that ends at the most recent play date
  end if;

  insert into public.player_stats as s (player_id, current_streak, longest_streak, last_played_date,
                                        total_played, total_correct, total_questions, best_combo, updated_at)
  values (_player_id, _current, _longest, _last, _played, _correct, _asked, _combo, now())
  on conflict (player_id) do update
    set current_streak = excluded.current_streak,
        longest_streak = excluded.longest_streak,
        last_played_date = excluded.last_played_date,
        total_played = excluded.total_played,
        total_correct = excluded.total_correct,
        total_questions = excluded.total_questions,
        best_combo = excluded.best_combo,
        updated_at = now();
end;
$$;

-- ============================================================================
-- E. GUEST HANDOFF: "Add my progress" / "Start fresh"
--    A guest is an anonymous auth user with rows of its own. Leaving for the
--    shared sign-in replaces that session with the account's, so before it
--    leaves the guest mints a one-time code (offer_guest_history). Only the
--    hash is stored; the code travels in the browser's sessionStorage and is
--    presented by the account afterwards. Expired, unknown or used codes say
--    nothing and move nothing. One decision per guest, ever.
-- ============================================================================
create table public.guest_handoffs (
  code_hash        text primary key,
  guest_player_id  uuid not null references public.players(id) on delete cascade,
  created_at       timestamptz not null default now(),
  expires_at       timestamptz not null default now() + interval '1 hour'
);
comment on table public.guest_handoffs is 'One-time, hashed codes a guest mints before the shared sign-in so the returning account can claim (or decline) that guest''s rows. Rows go when the guest player goes.';
alter table public.guest_handoffs enable row level security;   -- no policies: RPC only

create function public.guest_history_summary(_player_id uuid)
returns table(plays integer, finished integer, current_streak integer, longest_streak integer, favorites integer)
language sql stable security definer set search_path = public as $$
  select (select count(*)::int from public.game_records r where r.player_id = _player_id),
         (select count(*)::int from public.game_records r where r.player_id = _player_id and r.completed),
         coalesce((select s.current_streak from public.player_stats s where s.player_id = _player_id), 0),
         coalesce((select s.longest_streak from public.player_stats s where s.player_id = _player_id), 0),
         (select count(*)::int from public.puzzle_favorites f where f.player_id = _player_id)
$$;

-- Called by the GUEST (anonymous session) right before it leaves for sign-in.
create function public.offer_guest_history()
returns table(outcome text, code text, plays integer, finished integer, current_streak integer, longest_streak integer, favorites integer)
language plpgsql security definer set search_path = public, extensions as $$
#variable_conflict use_column
declare
  _uid uuid := auth.uid();
  _code text;
  _s record;
begin
  if _uid is null then
    return query select 'not_signed_in'::text, null::text, 0, 0, 0, 0, 0;
    return;
  end if;
  -- Only an anonymous guest that is not an account can hand anything over.
  if exists (select 1 from public.accounts a where a.user_id = _uid)
     or not exists (select 1 from auth.users u where u.id = _uid and u.is_anonymous) then
    return query select 'not_a_guest'::text, null::text, 0, 0, 0, 0, 0;
    return;
  end if;

  select * into _s from public.guest_history_summary(_uid);
  if _s.plays = 0 and _s.favorites = 0 then
    return query select 'no_history'::text, null::text, 0, 0, 0, 0, 0;
    return;
  end if;

  -- 192 random bits, URL-safe; only its hash is kept.
  _code := translate(rtrim(encode(gen_random_bytes(24), 'base64'), '='), '+/', '-_');
  delete from public.guest_handoffs where guest_player_id = _uid;
  insert into public.guest_handoffs (code_hash, guest_player_id)
  values (encode(digest(_code, 'sha256'), 'hex'), _uid);

  return query select 'ok'::text, _code, _s.plays, _s.finished, _s.current_streak, _s.longest_streak, _s.favorites;
end;
$$;

-- Called by the ACCOUNT after sign-in: is this code still good, and what would come across?
create function public.resolve_guest_handoff(_code text)
returns table(outcome text, plays integer, finished integer, current_streak integer, longest_streak integer, favorites integer, account_has_history boolean)
language plpgsql stable security definer set search_path = public, extensions as $$
#variable_conflict use_column
declare
  _uid uuid := public.wtf_uid();
  _h public.guest_handoffs;
  _s record;
begin
  if _uid is null then
    return query select 'not_signed_in'::text, 0, 0, 0, 0, 0, false;
    return;
  end if;
  if _code is null or length(_code) < 16 or length(_code) > 128 then
    return query select 'invalid'::text, 0, 0, 0, 0, 0, false;
    return;
  end if;
  select * into _h from public.guest_handoffs h where h.code_hash = encode(digest(_code, 'sha256'), 'hex');
  if not found then
    return query select 'invalid'::text, 0, 0, 0, 0, 0, false;
    return;
  end if;
  if _h.expires_at < now() then
    return query select 'expired'::text, 0, 0, 0, 0, 0, false;
    return;
  end if;
  select * into _s from public.guest_history_summary(_h.guest_player_id);
  return query select 'ok'::text, _s.plays, _s.finished, _s.current_streak, _s.longest_streak, _s.favorites,
    exists (select 1 from public.game_records r where r.player_id = _uid)
    or exists (select 1 from public.puzzle_favorites f where f.player_id = _uid);
end;
$$;

-- "Add my progress": the guest's rows change owner IN PLACE (same ids, nothing
-- created). Where both the guest and the account played the same puzzle the
-- better play is kept (finished beats unfinished, then the higher score, then
-- the account's); the other is removed and that puzzle's community stats are
-- rebuilt so one person is counted once. Favorites are united. The account's
-- counters are recomputed from the merged plays. The guest's anonymous auth
-- user is then deleted: it has nothing left and its session is gone.
create function public.import_guest_history(_code text)
returns table(outcome text, plays_moved integer, plays_dropped integer, favorites_moved integer)
language plpgsql security definer set search_path = public, extensions as $$
#variable_conflict use_column
declare
  _uid uuid := public.wtf_uid();
  _h public.guest_handoffs;
  _guest uuid;
  _conflicts text[];
  _moved integer := 0;
  _dropped integer := 0;
  _favs integer := 0;
  _pid text;
begin
  if _uid is null then
    return query select 'not_signed_in'::text, 0, 0, 0;
    return;
  end if;
  if _code is null or length(_code) < 16 or length(_code) > 128 then
    return query select 'invalid'::text, 0, 0, 0;
    return;
  end if;
  select * into _h from public.guest_handoffs h where h.code_hash = encode(digest(_code, 'sha256'), 'hex') for update;
  if not found then
    return query select 'invalid'::text, 0, 0, 0;
    return;
  end if;
  if _h.expires_at < now() then
    delete from public.guest_handoffs where code_hash = _h.code_hash;
    return query select 'expired'::text, 0, 0, 0;
    return;
  end if;
  _guest := _h.guest_player_id;
  if _guest = _uid or exists (select 1 from public.accounts a where a.user_id = _guest) then
    delete from public.guest_handoffs where code_hash = _h.code_hash;
    return query select 'invalid'::text, 0, 0, 0;
    return;
  end if;

  perform pg_advisory_xact_lock(hashtextextended('wtf_handoff:' || _guest::text, 0));
  -- The code is single-use whatever happens below.
  delete from public.guest_handoffs where guest_player_id = _guest;

  -- Community stats: rebuilt once per affected puzzle at the end, not per row.
  perform set_config('wtf.defer_stats', 'on', true);

  select array_agg(distinct g.puzzle_id) into _conflicts
    from public.game_records g
    join public.game_records a on a.puzzle_id = g.puzzle_id and a.player_id = _uid
   where g.player_id = _guest;

  -- Keep the better play per conflicting puzzle; drop the other.
  with both_sides as (
    select g.puzzle_id, g.id as guest_id, a.id as account_id,
           (g.completed and not a.completed) or (g.completed = a.completed and g.score > a.score) as guest_wins
      from public.game_records g
      join public.game_records a on a.puzzle_id = g.puzzle_id and a.player_id = _uid
     where g.player_id = _guest
  )
  delete from public.game_records r
   using both_sides b
   where r.id = case when b.guest_wins then b.account_id else b.guest_id end;
  get diagnostics _dropped = row_count;

  update public.game_records set player_id = _uid where player_id = _guest;
  get diagnostics _moved = row_count;

  -- Favorites: a puzzle both favorited counts once (the trigger decrements).
  delete from public.puzzle_favorites f
   where f.player_id = _guest
     and exists (select 1 from public.puzzle_favorites a where a.player_id = _uid and a.puzzle_id = f.puzzle_id);
  update public.puzzle_favorites set player_id = _uid where player_id = _guest;
  get diagnostics _favs = row_count;

  perform public.recompute_player_stats(_uid);

  if _conflicts is not null then
    foreach _pid in array _conflicts loop
      perform public.rebuild_puzzle_stats_for(_pid);
    end loop;
  end if;

  -- The guest has nothing left. GoTrue's cascades remove its sessions and
  -- refresh tokens; players cascades from auth.users; player_stats from players.
  delete from public.player_stats where player_id = _guest;
  delete from public.players where id = _guest;
  delete from auth.users where id = _guest;

  return query select 'imported'::text, _moved, _dropped, _favs;
end;
$$;

-- "Start fresh": the guest rows stay exactly where they are, still counted in
-- community stats, unreachable from this browser (its guest session is gone).
create function public.decline_guest_history(_code text)
returns table(outcome text)
language plpgsql security definer set search_path = public, extensions as $$
declare
  _uid uuid := public.wtf_uid();
  _rows integer;
begin
  if _uid is null then
    return query select 'not_signed_in'::text;
    return;
  end if;
  if _code is null or length(_code) < 16 or length(_code) > 128 then
    return query select 'invalid'::text;
    return;
  end if;
  delete from public.guest_handoffs where code_hash = encode(digest(_code, 'sha256'), 'hex');
  get diagnostics _rows = row_count;
  if _rows = 0 then
    return query select 'invalid'::text;
    return;
  end if;
  return query select 'started_fresh'::text;
end;
$$;

-- ============================================================================
-- F. DELETION
-- ============================================================================
create function public.delete_local_account(_user_id uuid) returns void
language plpgsql security definer set search_path = public as $$
declare
  _puzzles text[];
  _pid text;
begin
  if _user_id is null then
    return;
  end if;
  perform set_config('wtf.defer_stats', 'on', true);
  select array_agg(distinct puzzle_id) into _puzzles
    from public.game_records where player_id = _user_id and completed;

  -- Personal rows only. Every FK here points from the player's rows to content
  -- with ON DELETE RESTRICT/CASCADE in the content→player direction never the
  -- reverse, so nothing in `games` can be reached.
  delete from public.puzzle_favorites where player_id = _user_id;   -- counts trigger decrements
  delete from public.game_records     where player_id = _user_id;
  delete from public.player_stats     where player_id = _user_id;
  delete from public.guest_handoffs   where guest_player_id = _user_id;
  delete from public.admins           where user_id = _user_id;
  delete from public.accounts         where user_id = _user_id;
  delete from public.players          where id = _user_id;
  -- GoTrue's own cascades remove identities, sessions and refresh tokens.
  delete from auth.users where id = _user_id;

  if _puzzles is not null then
    foreach _pid in array _puzzles loop
      perform public.rebuild_puzzle_stats_for(_pid);
    end loop;
  end if;
end;
$$;

create function public.delete_my_account() returns boolean
language plpgsql security definer set search_path = public as $$
declare
  _uid uuid := public.wtf_uid();
begin
  if _uid is null then
    return false;
  end if;
  perform public.delete_local_account(_uid);
  return true;
end;
$$;

-- ============================================================================
-- G. GRANTS for everything this migration added: revoke, then grant by intent.
-- ============================================================================
revoke all on table public.accounts, public.admins, public.guest_handoffs from public, anon, authenticated;
grant all on table public.accounts, public.admins, public.guest_handoffs to service_role;

revoke all on function public.wtf_uid()                        from public, anon, authenticated;
revoke all on function public.account_email(uuid)              from public, anon, authenticated;
revoke all on function public.ensure_account()                 from public, anon, authenticated;
revoke all on function public.my_account()                     from public, anon, authenticated;
revoke all on function public.ping()                           from public, anon, authenticated;
revoke all on function public.is_wtf_admin()                   from public, anon, authenticated;
revoke all on function public.best_combo(jsonb)                from public, anon, authenticated;
revoke all on function public.recompute_player_stats(uuid)     from public, anon, authenticated;
revoke all on function public.guest_history_summary(uuid)      from public, anon, authenticated;
revoke all on function public.offer_guest_history()            from public, anon, authenticated;
revoke all on function public.resolve_guest_handoff(text)      from public, anon, authenticated;
revoke all on function public.import_guest_history(text)       from public, anon, authenticated;
revoke all on function public.decline_guest_history(text)      from public, anon, authenticated;
revoke all on function public.delete_local_account(uuid)       from public, anon, authenticated;
revoke all on function public.delete_my_account()              from public, anon, authenticated;

grant execute on function public.wtf_uid()                     to anon, authenticated, service_role;
grant execute on function public.ping()                        to anon, authenticated, service_role;
grant execute on function public.is_wtf_admin()                to anon, authenticated, service_role;
grant execute on function public.ensure_account()              to authenticated, service_role;
grant execute on function public.my_account()                  to authenticated, service_role;
grant execute on function public.offer_guest_history()         to authenticated, service_role;   -- guests are `authenticated` too
grant execute on function public.resolve_guest_handoff(text)   to authenticated, service_role;
grant execute on function public.import_guest_history(text)    to authenticated, service_role;
grant execute on function public.decline_guest_history(text)   to authenticated, service_role;
grant execute on function public.delete_my_account()           to authenticated, service_role;
grant execute on function public.account_email(uuid)           to service_role;
grant execute on function public.best_combo(jsonb)             to service_role;
grant execute on function public.recompute_player_stats(uuid)  to service_role;
grant execute on function public.guest_history_summary(uuid)   to service_role;
grant execute on function public.delete_local_account(uuid)    to service_role;


-- ---------------------------------------------------------------------------
-- 2. 0002_wtf_player_lockdown.sql
-- ---------------------------------------------------------------------------
-- ============================================================================
--  WTF Trivia: player-table lockdown (the pre-existing "L1" fix, now required)
-- ============================================================================
--  This is supabase/puzzle_id_cutover/L1_security_lockdown_NOT_YET_APPLIED.sql
--  (audit A0, 2026-09-28), unchanged in intent. It was optional while every
--  player row was a guest's. With shared accounts, players.email holds real
--  people's addresses, so the permissive duplicates have to go before Phase 2.
--
--  What it does: removes ONLY the old "anyone" policies that sit next to the
--  correct own-row policies on players, game_records and player_stats.
--  Postgres allows a request if ANY policy allows it, so today anyone can read
--  every player row (emails), and read/edit every play and streak row. The
--  own-row policies that stay already cover everything the app does: guests
--  and accounts alike have a real session and only touch their own rows.
--
--  Content (games) is NOT touched here; the games policies are migration 0003.
--  Zero rows change. Guarded: aborts if an own-row policy were missing.
-- ============================================================================

do $$
declare missing text;
begin
  select string_agg(t || ': ' || p, ', ') into missing
  from (values
    ('players', 'players own profile'), ('players', 'players create profile'), ('players', 'players update profile'),
    ('game_records', 'game records own rows'), ('game_records', 'game records insert own rows'),
    ('game_records', 'game records update own rows'),
    ('player_stats', 'player stats own rows'), ('player_stats', 'player stats insert own rows'),
    ('player_stats', 'player stats update own rows')
  ) v(t, p)
  where not exists (select 1 from pg_policies where schemaname = 'public' and tablename = v.t and policyname = v.p);
  if missing is not null then
    raise exception '0002 aborted: own-row policies missing: %', missing;
  end if;
end $$;

-- Players: no more reading everyone's row (emails), no more creating rows for other ids.
drop policy if exists "Players can read own row"      on public.players;
drop policy if exists "Anyone can create a player"    on public.players;

-- Play records: only your own.
drop policy if exists "Players can read own records"   on public.game_records;
drop policy if exists "Players can insert own records" on public.game_records;
drop policy if exists "Players can update own records" on public.game_records;

-- Streak stats: only your own.
drop policy if exists "Players can read own stats"   on public.player_stats;
drop policy if exists "Players can insert own stats" on public.player_stats;
drop policy if exists "Players can update own stats" on public.player_stats;

-- Table privileges on the player tables, set explicitly rather than inherited
-- from the project default (which granted anon everything). The app never
-- deletes a play, a stats row or a player from the browser.
revoke all on table public.players, public.game_records, public.player_stats from anon;
revoke delete, truncate, references, trigger on table public.players, public.game_records, public.player_stats from authenticated;
grant select, insert, update on table public.players, public.game_records, public.player_stats to authenticated;

-- Community stats are read-only for clients; only the trigger (owner) writes them.
revoke all on table public.puzzle_stats from anon, authenticated;
grant select on table public.puzzle_stats to anon, authenticated;

-- Stats functions: only the database's own triggers run them (already so on the
-- hosted project; repeated here so a blank project matches).
revoke execute on function public.rebuild_puzzle_stats_for(text) from public, anon, authenticated;
revoke execute on function public.rebuild_puzzle_stats()         from public, anon, authenticated;
revoke execute on function public.handle_completed_game_record() from public, anon, authenticated;
revoke execute on function public.game_records_assign_puzzle()   from public, anon, authenticated;


-- ---------------------------------------------------------------------------
-- 3. the migration ledger (what `supabase db push` would have written)
-- ---------------------------------------------------------------------------
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version text primary key,
  statements text[],
  name text
);
insert into supabase_migrations.schema_migrations (version, name)
values ('0001', 'wtf_baseline'), ('0002', 'wtf_player_lockdown')
on conflict (version) do nothing;
